name: docs
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - openmm=7.6
  - scipy
  - numpy
  - parmed
  - pyyaml
  
  # Documentation
  - sphinx~=6.2.1 #https://github.com/kivy/kivy/issues/8230, had the same problem
  - sphinx_rtd_theme

    # Testing
  #- pytest
  #- pytest-cov
  #- codecov

    # Pip-only installs
  - pip:
    # - git+https://github.com/ParmEd/ParmEd.git
    # Doku emojis
    - sphinxemoji
    
