name: isort

on: [pull_request, workflow_dispatch]

permissions:
  checks: write
  contents: write
  
jobs:
  isort:
    name: Run linters
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
         # ref: ${{ github.ref }}
        
      #- name: Set up Python
      #  uses: actions/setup-python@v1
      #  with:
      #    python-version: 3.9
          
      - name: Install Python dependencies
        run: pip install isort
        
      - name: Run python-isort
      # You may pin to the exact commit or the version.
        # uses: isort/isort-action@f555d1d11ca0529654eb6d1f017f9e4a269ffa7f
        uses: isort/isort-action@v1.0.0
        with:
          # Version of isort to use
          # isortVersion: # optional, default is latest
          # files or directories to sort
          sortPaths: . # optional, default is .
          # isort configuration options
          configuration: --diff # optional, default is --check-only --diff
          # path(s) to requirements files that should be installed to properly configure third-party imports
          # requirementsFiles: # optional, default is 
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          #git remote set-url origin https://florianjoerg:${{ secrets.GITHUB_TOKEN }}@github.com/florianjoerg/protex.git
          #git fetch --no-tags --depth=1 origin ${{ github.ref }}
          #git branch --force ${{ github.ref }} --track origin/${{ github.ref }}
          #git checkout ${{ github.ref }}
          git pull
          git add -A && git diff-index --cached --quiet HEAD || git commit -m 'isort'
          git push
          # git commit -m "isort" -a

      #- name: Push changes
      #  uses: ad-m/github-push-action@master
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    branch: ${{ github.ref }}
