name: lint_python

on: [pull_request, workflow_dispatch]

permissions:
  checks: write
  contents: write
  
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          
      - name: Install Python dependencies
        run: pip install flake8 pep8-naming black
        
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          black_dir: "protex/"
          black_args: '--extend-exclude="(forcefield/*|scripts/*|_version.py)"'
          auto_fix: true
          flake8: true
          flake8_dir: "protex/"
          flake8_args: "--exclude=scripts,forcefield,_version.py --max-line-length=88 --extend-ignore=E203 --exit-zero"
      - name: python-isort
        # You may pin to the exact commit or the version.
        # uses: isort/isort-action@f555d1d11ca0529654eb6d1f017f9e4a269ffa7f
        uses: isort/isort-action@v1.0.0
        with:
          # Version of isort to use
          # isortVersion: # optional, default is latest
          # files or directories to sort
          sortPaths: . # optional, default is .
          # isort configuration options
          # configuration: # optional, default is --check-only --diff
          # path(s) to requirements files that should be installed to properly configure third-party imports
          # requirementsFiles: # optional, default is 

        
      #- name: Setup flake8 annotations
      #  uses: rbialon/flake8-annotations@v1
      #- name: Lint with flake8
      #  run: |
      #    pip install flake8 pep8-naming
      #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


