name: Lint

on:
  push:
    paths:
      - '*.py'

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.4
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
#name: lint_python
#on: [pull_request, push, workflow_dispatch]
#jobs:
#  lint_python:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-python@v3
#      - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade safety
#      - run: bandit --recursive --skip B101 . || true  # B101 is assert statements
#      - run: black --check . || true
#      - run: codespell || true  # --ignore-words-list="" --skip=""
#      - run: flake8 . --exclude protex/scripts --count --select=E9,F63,F7,F82 --show-source --statistics
#      - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --show-source --statistics
#      - run: isort --check-only --profile black . || true
#      - run: pip install -r requirements.txt || true
#      - run: mypy --install-types --non-interactive . || true
#      - run: pytest . || true
#     - run: pytest --doctest-modules . || true
#     - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
#     - run: safety check
