name: lint_python

on: [pull_request, workflow_dispatch]

permissions:
  checks: write
  contents: write
  
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          
      - name: Install Python dependencies
        run: pip install flake8 pep8-naming black
        
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          flake8: true
          flake8_args: "--exclude=devtools,protex/scripts,protex/forcefield,docs/ --max-line-length=88 --extend-ignore=E203"
          black: true
          black_args: "--exclude=devtools|docs"
        
        
        
        
      #- name: Setup flake8 annotations
      #  uses: rbialon/flake8-annotations@v1
      #- name: Lint with flake8
      #  run: |
      #    pip install flake8 pep8-naming
      #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


      
#name: lint_python
#on: [pull_request, push, workflow_dispatch]
#jobs:
#  lint_python:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-python@v3
#      - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade safety
#      - run: bandit --recursive --skip B101 . || true  # B101 is assert statements
#      - run: black --check . || true
#      - run: codespell || true  # --ignore-words-list="" --skip=""
#      - run: flake8 . --exclude protex/scripts --count --select=E9,F63,F7,F82 --show-source --statistics
#      - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --show-source --statistics
#      - run: isort --check-only --profile black . || true
#      - run: pip install -r requirements.txt || true
#      - run: mypy --install-types --non-interactive . || true
#      - run: pytest . || true
#     - run: pytest --doctest-modules . || true
#     - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
#     - run: safety check
